AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance for backend with Docker and SSH access and frontend via s3 bucket

Parameters:
  SshPublicKey:
    Type: String
    Description: Public SSH key for EC2 access
  MongoUri:
    Type: String
    NoEcho: true  # Hides value in AWS logs
  MongoDb:
    Type: String
  MongoCollection:
    Type: String
  DockerImage:
    Type: String

Resources:
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and backend port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  BackendInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Allows connection via Session Manager in Console
      Policies:
        - PolicyName: ECRPullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"

  BackendInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BackendInstanceRole

  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0387413ed05eb20af # Amazon Linux 2023
      IamInstanceProfile: !Ref BackendInstanceProfile
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # Update system
          dnf update -y

          # install and configure docker
          dnf install -y docker
          systemctl enable docker
          systemctl start docker
          usermod -aG docker ec2-user

          # SSH public key
          mkdir -p /home/ec2-user/.ssh
          echo "${SshPublicKey}" >> /home/ec2-user/.ssh/authorized_keys
          chmod 700 /home/ec2-user/.ssh
          chmod 600 /home/ec2-user/.ssh/authorized_keys
          chown -R ec2-user:ec2-user /home/ec2-user/.ssh

          docker run -d \
            --name xkcd-backend \
            --restart always \
            -p 8000:8000 \
            -e MONGO_URI='${MongoUri}' \
            -e MONGO_DB='${MongoDb}' \
            -e MONGO_COLLECTION='${MongoCollection}' \
            ${DockerImage}

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        # ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt FrontendBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed CachingOptimized

Outputs:
  BackendPublicIp:
    Value: !GetAtt BackendInstance.PublicIp

  BackendPublicDns:
    Value: !GetAtt BackendInstance.PublicDnsName

  BucketName:
    Value: !Ref FrontendBucket

  CloudFrontUrl:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"