AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance for backend with Docker and SSH access and frontend via s3 bucket

Parameters:
  SshPublicKey:
    Type: String
    Description: Public SSH key for EC2 access
  MongoUri:
    Type: String
    NoEcho: true  # WICHTIG: Versteckt die Eingabe in den AWS Logs!
  MongoDb:
    Type: String
  MongoCollection:
    Type: String

Resources:
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and backend port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

# 1. Die IAM Rolle für die EC2 Instanz
  BackendInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # Erlaubt Zugriff via Session Manager (kein SSH nötig)

  # 2. Das Instance Profile (verknüpft Rolle mit der Hardware)
  BackendInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BackendInstanceRole

  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP and Backend Port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80       # Neu: Standard HTTP
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000     # Dein FastAPI Port
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0387413ed05eb20af # Amazon Linux 2023
      IamInstanceProfile: !Ref BackendInstanceProfile # HIER wird die Rolle zugewiesen!
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # System aktualisieren
          dnf update -y

          # Docker Repository hinzufügen
          # folgender Befehl unnötig, weil schon in AL2023 direkt enthalten
          # dnf install -y amazon-linux-extras

          # Docker installieren (AL2023)
          dnf install -y docker

          systemctl enable docker
          systemctl start docker

          # ec2-user zu Docker-Gruppe hinzufügen
          usermod -aG docker ec2-user

          # SSH Key konfigurieren
          mkdir -p /home/ec2-user/.ssh
          echo "${SshPublicKey}" >> /home/ec2-user/.ssh/authorized_keys
          chmod 700 /home/ec2-user/.ssh
          chmod 600 /home/ec2-user/.ssh/authorized_keys
          chown -R ec2-user:ec2-user /home/ec2-user/.ssh

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        # ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"




Outputs:
  BackendPublicIp:
    Value: !GetAtt BackendInstance.PublicIp

  BackendPublicDns:
    Value: !GetAtt BackendInstance.PublicDnsName

  BucketName:
    Value: !Ref FrontendBucket